version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports: ["5432:5432"]
    healthcheck: {test: ["CMD-SHELL","pg_isready -U ${PGUSER}"], interval: 5s, retries: 10}

  minio:
    image: minio/minio:RELEASE.2024-05-28T17-19-04Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${OBJECT_STORE_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${OBJECT_STORE_SECRET_KEY}
    ports: ["9000:9000","9001:9001"]

  redis:
    image: redis:7
    ports: ["6379:6379"]

  transport-registry:
    build: ./services/transport-registry
    environment: [PGHOST,PGUSER,PGPASSWORD,PGDATABASE,PGPORT,OBJECT_STORE_ENDPOINT,OBJECT_STORE_BUCKET,DSU_SIGNER_BASE]
    volumes:
      - ../libs/edg_numerics:/opt/edg_numerics:ro
    ports: ["${TRANSPORT_REGISTRY_PORT}:8080"]
    depends_on: [postgres, minio]

  holonomy-engine:
    build: ./services/holonomy-engine
    environment:
      - EVENT_BUS_URL=redis://redis:6379/0
    volumes:
      - ../libs/edg_numerics:/opt/edg_numerics:ro
    ports: ["${HOLONOMY_ENGINE_PORT}:8080"]
    depends_on: [transport-registry, redis]

  loop-registry:
    build: ./services/loop-registry
    environment:
      - EVENT_BUS_URL=redis://redis:6379/0
    ports: ["${LOOP_REGISTRY_PORT}:8080"]
    depends_on: [postgres, redis]

  residual-service:
    build: ./services/residual-service
    volumes:
      - ../libs/edg_numerics:/opt/edg_numerics:ro
    ports: ["${RESIDUAL_SERVICE_PORT}:8080"]
    depends_on: [transport-registry]

  lens-flow:
    build: ./services/lens-flow
    ports: ["${LENS_FLOW_PORT}:8080"]
    depends_on: [holonomy-engine]

  dsu-signer:
    build: ./services/dsu-signer
    ports: ["${DSU_SIGNER_PORT}:8080"]

  dashboard-api:
    build: ./services/dashboard-api
    ports: ["${DASHBOARD_API_PORT}:8080"]
    depends_on: [holonomy-engine, loop-registry, residual-service]
